<?php

/** @var \MolokaiStudio\GoogleCustomerReviews\ViewModel\Survey $viewModel */
$viewModel = $block->getViewModel();

?>

<?php if ($viewModel->isEnabled()): ?>
<!-- BEGIN GCR Opt-in Module Code -->
<script src="https://apis.google.com/js/platform.js?onload=renderOptIn"
        async defer>
</script>

<script>
    window.renderOptIn = function() {
        window.gapi.load('surveyoptin', function() {
            window.gapi.surveyoptin.render(
                {
                    "merchant_id":"<?php echo $viewModel->getMerchantId(); ?>",
                    "order_id": "<?php echo $viewModel->getOrderId(); ?>",
                    "email": "<?php echo $viewModel->getCustomerEmail(); ?>",
                    "delivery_country": "<?php echo $viewModel->getDeliveryCountry(); ?>",
                    "estimated_delivery_date": "<?php echo $viewModel->getEstimatedDeliveryDate(); ?>",
                    <?php if ($viewModel->showProductsInSurvey()) : ?>
                    "products": <?php echo json_encode($viewModel->getProductsGtins()); ?>,
                    <?php endif; ?>
                    "opt_in_style": "<?php echo $viewModel->getPosition(); ?>"
                });
        });
    }
</script>
<!-- END GCR Opt-in Module Code -->

<?php endif; ?>